# Generated by Django 4.0.4 on 2022-06-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='highScore',
            field=models.IntegerField(default=0),
        ),
    ]
