# Generated by Django 4.0.4 on 2022-06-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile_highscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dateAcquired',
            field=models.DateField(blank=True, null=True),
        ),
    ]
